version: '3'

services:
  db:
    build: ./MongoDocker
    command : mongod
    ports:
      - "27017:27017"
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000 
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    depends_on:
      - db
